[ci skip] first draft of the `MoscotKernel`
theislab/cellrank pull request #1016
Opened 2023-03-31 16:20 UTC by MUCDK

replaces #987

2023-04-06 14:58 UTC, MUCDK commented
I currently only test for `MoscotKernel.load` until we have agreed on how we want to enable instantiating it.

Moreover, there are some tests failling, but they are very cellrank-specific, so would appreciate your help @Marius1311 @WeilerP @michalk8 .

2023-04-06 15:34 UTC, michalk8 commented on requirements.txt
> +git+https://github.com/theislab/moscot
This cannot be here, please use just `moscot`.
Re failing tests: think they are coming from `scvelo`, try pinning `pandas<2` here temporarily.

2023-04-10 12:13 UTC, michalk8 requested changes

2023-04-10 12:13 UTC, michalk8 commented on requirements.txt
> +moscot
This should be an optional requirement.

2023-04-10 12:13 UTC, michalk8 commented on requirements.txt
> +pandas==1.5.0
<2, until `scvelo` is fixed.

2023-04-10 12:13 UTC, michalk8 commented on tests/conftest.py
> +from moscot.datasets import simulate_data
This will cause an issue if `moscot` is not installed, you might need to defined these fixtures differently.

2023-04-10 12:13 UTC, michalk8 commented on tests/test_external.py
> +def _moscot_not_installed() -> bool:
This is also defined elsewhere, please remove one definition.

2023-04-10 12:13 UTC, michalk8 commented on tests/test_moscot_interface.py
> +@moscot_not_installed_skip
You can skip the whole file using `pytest` without the need to mark it like this.

2023-04-10 12:13 UTC, michalk8 commented on tests/test_moscot_interface.py
> +    from moscot.problems import LineageProblem, TemporalProblem, SpatioTemporalProblem
If you skip the whole file, this can be on top I think.

2023-04-10 12:13 UTC, michalk8 commented on tests/test_moscot_interface.py
> +        pass
This test needs to be finished (or removed).

2023-04-10 12:13 UTC, michalk8 commented on tests/test_moscot_interface.py
> +    @pytest.mark.parametrize("backward", [True, False])
I don't think we need to parametrize this by `backward`, esp. if you're not checking for it in the test.

2023-04-10 12:13 UTC, michalk8 commented on cellrank/kernels/_moscot_kernel.py
> +    def compute_transition_matrix(
I don't think there's a need to override this, just use the `_compute_tmap` API which should provide you with everything.

Regarding the `tmaps` argument, I think this is generic enough that it should be in the `TransportKernel` class, as a class method, e.g.,:
```python
@classmethod
def from_transport_maps(cls, adata: AnnData, tmaps: Dict[..., ...], **kwargs: Any) -> "TransportMapKernel":
    # do some checking whether all tmaps are present and synced with `adata`, etc.
    kernel = cls(adata, ...) 
    kernel._tmaps = tmaps
    kernel._is_precomputed = True  # needs to be set to false in `TransportMapKernel.__init__`
    return kernel
```

and then in `compute_transition_matrix`, you'd have:
```python
if not self._is_precomputed:
    self._tmaps = {}
    for t1, t2 in tqdm(timepoints, unit="time pair"):
        tmat = self._compute_tmap(t1, t2, **kwargs)
        self.transport_maps[t1, t2] = self._tmat_to_adata(t1, t2, tmat)
```

2023-04-10 12:13 UTC, michalk8 commented on cellrank/kernels/_moscot_kernel.py
> +    def load(
In light of the other comment, if you have `from_transport_maps`, you can then have
```python
@classmethod
def from_moscot(cls, problem: "CompoundProblem", **kwargs: Any):
    tmaps = problem.solution.items()
    return cls.from_transport_maps(problem.adata, tmaps=tmaps, time_key=problem.time_key, **kwargs)
```

2023-04-23 14:29 UTC, MUCDK commented
I don't think we can simply override `_compute_tmap`, as we need different arguments in `compute_transition_matrix`. 
I.e., the signature of `MoscotKernel.compute_transition_matrix` should be along the lines of 
```python
def compute_transition_matrix(
        self,
        tmaps: Optional[Dict[Tuple[float, float], Type[BaseSolverOutput]]] = None,
        threshold: Optional[str] = None,
        self_transitions: Union[
            Literal["uniform", "diagonal", "connectivities", "all"],
            Sequence[float],
        ] = "connectivities",
        conn_weight: Optional[float] = None,
        conn_kwargs: Mapping[str, Any] = MappingProxyType({}),
        **kwargs: Any,
```

I.e. we need `tmaps` as additional argument compared to `TransportMapKernel.compute_transition_matrix()`

2023-06-02 14:14 UTC, closed without merging