Update docs
theislab/cellrank pull request #1227
Opened 2024-09-26 08:15 UTC by WeilerP

**IMPORTANT: Please search among the [Pull requests](../pulls) before creating one.**

## Description

- Update overview figures
- Drop email support
- Update citations

## Closes

Closes #1226.

2024-09-26 09:13 UTC, michalk8 requested changes
Thanks a lot @WeilerP , just some minor comments!

2024-09-26 09:13 UTC, michalk8 commented on docs/_static/img/dark_mode_overview.png
I think this PNG is too large (both in HxW, and in size) - it takes time to load on the page. Could you please reduce the height/width, plus optionally [optipng](https://optipng.sourceforge.net/).

2024-09-26 09:13 UTC, michalk8 commented on docs/_static/img/light_mode_overview.png
Same here, too large, could you please reduce the size? Also, it would be great if the 2 PNGs were aligned, the dark mode one contains some extra padding on top/bottom and it's noticeable when changing between light/dark.

2024-09-26 09:26 UTC, michalk8 commented on docs/_static/img/dark_mode_overview.png
Also if possible, having the background transparent would be best!

2024-09-26 09:27 UTC, WeilerP commented on docs/_static/img/light_mode_overview.png
Let me look into it. They should be aligned; I'll check what went wrong.

2024-09-26 09:42 UTC, WeilerP commented on docs/_static/img/light_mode_overview.png
Where do you see that they don't align? They look good to me.

2024-09-26 11:38 UTC, Marius1311 commented
Thanks @WeilerP! I think on the landing page, we should have a direct link to our published papers, not just a citation. Otherwise, users have to first click the citation, then they get forwarded to the hughe list of references, and then they need to click again. 

The links to our papers should be prominently places, and I think users should get to the published articles with a single click.

2024-09-26 11:39 UTC, Marius1311 commented
What about tutorials - should we also update them, or start with just the docs for now? They also contain outdated figures.

2024-09-26 12:46 UTC, michalk8 commented on docs/_static/img/light_mode_overview.png
Looks great now, thanks!

2024-09-26 12:46 UTC, michalk8 commented on docs/_static/img/dark_mode_overview.png
Thanks, looks much better!

2024-09-26 12:51 UTC, michalk8 approved these changes
From my side LGTM!, but as Marius says, we should also update the tutorials.
As for the direct citation on the landing page, no strong opinion there, think it's ok as it is now (it's prominent enough).

2024-09-26 13:49 UTC, WeilerP commented on docs/index.rst
> +- `CellRank 2: unified fate mapping in multiview single-cell data <https://doi.org/10.1038/s41592-024-02303-9>`
What do you think, @Marius1311?

2024-09-27 09:18 UTC, Marius1311 approved these changes
Looks great. Do you want to mention that we won the Helmholtz Software Award? It think it's a great achievement.

2024-09-27 09:18 UTC, Marius1311 commented on README.rst
Looks good!

2024-09-27 09:18 UTC, Marius1311 commented on docs/index.rst
> +- `CellRank 2: unified fate mapping in multiview single-cell data <https://doi.org/10.1038/s41592-024-02303-9>`
looks good!

2024-09-27 11:55 UTC, WeilerP commented
> Looks great. Do you want to mention that we won the Helmholtz Software Award? It think it's a great achievement.

Let's wait until we officially received it, okay?

2024-09-27 11:56 UTC, merged

2024-09-27 12:05 UTC, Marius1311 commented
Up to you, but we officially won it, just the ceremony is outstanding: https://www.hifis.net/news/2024/07/18/sw-award-final.html