General pt kernel
theislab/cellrank pull request #514
Opened 2021-03-06 22:21 UTC by michalk8

**IMPORTANT: Please search among the [Pull request](../pulls) before creating one.**

## Title

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)

## Description

Adds soft/hard/custom threhdolding for cells in PT's past for `PseudotimeKernel`.
@Marius1311 would be great if you could check this out and compare it with VIA's implementation [here](https://github.com/ShobiStassen/VIA/blob/master/VIA/core.py#L635).
Briefly, I've kept all the constant the same, except for `nu` (now is 0.5, orig. was 1 for the gen. [logistic regression](https://en.wikipedia.org/wiki/Generalised_logistic_function)) + I do 95% winsorization, instead of 90% on the KNN weights.
You can set the thresholding as `threshold_scheme={'soft','hard'}` or pass a function which has the following signature:
`(cell_pseudotime: float, neigh_pseudotime: np.ndarray, neigh_dist: np.ndarray, **kwargs: Any) -> np.ndarray`
(not sure about the naming, `neigh_dist` are the `KNN` weights, should be renamed).

## How has this been tested?

No tests yet.

## Closes

closes #504

TODO:
- [ ] tests
- [ ] determine which parameters to expose
- [ ] update docs (@Marius1311 I leave this up to you)

2021-03-08 16:11 UTC, Marius1311 requested changes
Very elegant solution @michalk8. I suggest
- removing the clipping
- removing the nu parameter (fixing it to 1)
- making sure weights are in [0, 1] 
I detail this in my comments. Once this is done, I will take care of the docstrings and test this on some data.

2021-03-08 16:11 UTC, Marius1311 commented on cellrank/tl/kernels/_pseudotime_schemes.py
> +        weights[past_ixs] = 1.0 / ((1.0 + np.exp(b * dt)) ** (1.0 / nu))
They also seem to be using nu=1 in their implementation.

2021-03-09 08:48 UTC, michalk8 commented on cellrank/tl/kernels/_pseudotime_schemes.py
> +        b: float = 20.0,
b=1 is for `"using the pseudotime calculated from lazy-jumping walk`"
b=20 is for `" using the refined MCMC Psuedotimes before calculating lineage likelihood paths"`

2021-03-09 08:49 UTC, michalk8 commented on cellrank/tl/kernels/_pseudotime_schemes.py
> +            return neigh_dist * 0.5
It does matter: `sigmoid(0) = 0.5` i.e. when the current point is the same (or very close) w.r.t. to PT.

2021-03-09 08:51 UTC, michalk8 commented on cellrank/tl/kernels/_pseudotime_schemes.py
> +        )
I can send you some figures I have where I did a grid search so you can see for yourself if it's necessary.
I would say keep it (i.e. cells which are further from each other should have greater KNN distance between them, this
dampens these "outliers" if weights are not sufficiently small).

2021-03-09 12:21 UTC, Marius1311 commented on cellrank/tl/kernels/_pseudotime_schemes.py
> +        nu: float = 0.5,
Hi Mike, please check your mattermost, I send you exactly these plots yesterday already and made the suggestion based on that.

2021-03-10 17:47 UTC, Marius1311 commented
What's the status here, only tests missing?

2021-03-11 00:24 UTC, michalk8 commented
> What's the status here, only tests missing?

From my side, it's the tests, from your side, it would be to polish the docstrings of `PseudotimeKernel` + of the schemes (I've alreay included the VIA citation)

2021-03-11 07:19 UTC, Marius1311 commented
Nice, will tend to this after my PR today!

2021-03-11 07:38 UTC, Marius1311 commented
Estimators don't like the pseudotime kernel yet, running
```
from cellrank.tl.kernels import PseudotimeKernel
from cellrank.tl.estimators import GPCCA

kernel = PseudotimeKernel(adata, time_key='gcs_pseudotime', check_connectivity=True)
kernel.compute_transition_matrix(threshold_scheme='hard', k=3)

g_fwd = GPCCA(kernel)
```
raises
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-a0174fcf3fc7> in <module>
----> 1 g_fwd = GPCCA(kernel)
      2 print(g_fwd)

~/Projects/cellrank/cellrank/tl/estimators/_base_estimator.py in __init__(self, obj, inplace, read_from_adata, obsp_key, g2m_key, s_key, write_to_adata, key)
    103         from anndata import AnnData
    104 
--> 105         super().__init__(obj, obsp_key=obsp_key, key=key, write_to_adata=write_to_adata)
    106 
    107         if isinstance(obj, (KernelExpression, AnnData)) and not inplace:

~/Projects/cellrank/cellrank/tl/estimators/_property.py in __init__(self, *args, **kwargs)
    864 
    865     def __init__(self, *args, **kwargs):
--> 866         super().__init__(*args, **kwargs)
    867 
    868         self._is_irreducible = None  # no need to refactor these

~/Projects/cellrank/cellrank/tl/estimators/_property.py in __init__(self, obj, key, obsp_key, write_to_adata)
    213             self._kernel = PrecomputedKernel(obj.obsp[obsp_key], adata=obj)
    214         else:
--> 215             raise TypeError(
    216                 f"Expected an object of type `KernelExpression`, `numpy.ndarray`, `scipy.sparse.spmatrix` "
    217                 f"or `anndata.AnnData`, got `{type(obj).__name__!r}`."

TypeError: Expected an object of type `KernelExpression`, `numpy.ndarray`, `scipy.sparse.spmatrix` or `anndata.AnnData`, got `'PseudotimeKernel'`.
```

2021-03-11 07:56 UTC, michalk8 commented
> Estimators don't like the pseudotime kernel yet, running

This is an issue with jupyter + autoreload (can't reproduce this).

2021-03-11 08:43 UTC, Marius1311 commented
Okay sorry, my mistake then!

2021-03-11 08:45 UTC, Marius1311 commented
Okay, you're right, restarting my kernel solved this, really sorry!

2021-03-12 12:57 UTC, Marius1311 commented
The docstrings should be done @michalk8 - let me know if I missed anyting!

2021-03-13 18:11 UTC, merged

2021-03-15 09:29 UTC, Marius1311 commented
Thanks for adding the tests!