Restrict embedding projection to knn based kernels
theislab/cellrank pull request #733
Opened 2021-09-01 19:47 UTC by WeilerP

**IMPORTANT: Please search among the [Pull requests](../pulls) before creating one.**

## Title

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] New feature (non-breaking change which adds functionality)

## Description

Restricts computation of embedding projection to kNN based kernels.

## How has this been tested?

`TestOTKernel` and `TestWOTKernel` are extended by one unit test each to verify that expected error is thrown.

## Have release notes been modified?

## Closes

Closes #668.

2021-09-01 20:04 UTC, WeilerP commented
I'll rebase once #734 has been solved.

2021-09-01 20:10 UTC, michalk8 requested changes

2021-09-02 05:09 UTC, WeilerP commented on cellrank/tl/kernels/_base_kernel.py
>          kernels_w_conn = [kernel for kernel in self.kernels if kernel._conn is not None]
Oh yes, you're right!

2021-09-02 15:14 UTC, michalk8 approved these changes

2021-09-02 15:18 UTC, michalk8 commented
@WeilerP I'd use `{kernel!r}` since `__repr__` doesn't print out the params, this should fix the `match=...` in those tests. Afterwards, it can be merged.

2021-09-07 07:03 UTC, Marius1311 commented
Really nice! Glad to finally close this issue!

2021-09-08 10:36 UTC, michalk8 commented
@WeilerP think this can be merged, right?

2021-09-08 11:59 UTC, WeilerP commented
> @WeilerP think this can be merged, right?

Yes!

2021-09-08 12:13 UTC, merged