Feat/realtimekernel transition matrix warning
theislab/cellrank pull request #876
Opened 2022-05-26 18:37 UTC by WeilerP

**IMPORTANT: Please search among the [Pull requests](../pulls) before creating one.**

## Description
Throws an error when calculating the transition matrix with the `RealtimeKernel` with `self_transitions` provided but not `conn_weight` (or incorrectly) before calculating the transport maps.

## How has this been tested?

## Closes
Closes #875

2022-05-29 22:17 UTC, michalk8 requested changes

2022-05-29 22:17 UTC, michalk8 commented on cellrank/external/kernels/_wot_kernel.py
> +            (self_transitions is not None)
This check only makes sense when `self_transitions == 'all'` or is a tuple (`'uniform'/'diagonal'/'connectivities'` don't need the `conn_weight`).
Please change this check.

2022-06-14 10:27 UTC, michalk8 commented
@WeilerP what's the status of this PR?

2022-06-21 12:04 UTC, Marius1311 commented
Anything missing here?

2022-10-04 10:22 UTC, michalk8 commented
closed in favor of #950

2022-10-04 10:22 UTC, closed without merging